# Generated by Django 4.2.6 on 2023-10-27 20:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given", models.CharField(max_length=32)),
                ("family", models.CharField(max_length=32)),
                (
                    "nhs_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be 10 digits only", regex="^\\d{10}$"
                            )
                        ],
                    ),
                ),
                ("birthdate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept_code", models.BigIntegerField()),
                ("significant", models.BooleanField()),
                ("active", models.BooleanField()),
                ("date", models.DateField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="EHR.person"
                    ),
                ),
            ],
        ),
    ]
